# Generated by Django 3.2.15 on 2023-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='brand_name')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Brand_URL')),
            ],
            options={
                'verbose_name': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='ElectroType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='electro_type')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тип',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='UseFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='used_for')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='pro_or_home_URL')),
            ],
            options={
                'verbose_name': 'Назначение',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('subcategory', models.ManyToManyField(to='store.SubCategory')),
            ],
            options={
                'verbose_name': 'Основная категория',
            },
        ),
    ]
